rootProject.name = "ai-dev-kit"

include("ai-dev-kit-eval")
include("examples")
include("ai-dev-kit-plugin")
include("tracing-providers")
include("tracing-providers:tracing-providers-core")
include("tracing-providers:tracing-providers-openai")
include("tracing-providers:tracing-providers-anthropic")
include("tracing-providers:tracing-providers-gemini")
include("tracing-providers:tracing-providers-ktor")
include("tracing-providers:tracing-providers-test-utils")
include("ai-dev-kit-tracking-providers")
include("ai-dev-kit-tracking-providers:ai-dev-kit-tracking-langfuse")
include("ai-dev-kit-tracking-providers:ai-dev-kit-tracking-wandb")
includeBuild("ai-dev-kit-plugin/ai-dev-kit-trace-gradle")
includeBuild("ai-dev-kit-plugin/ai-dev-kit-trace-plugin")
