package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'Tests'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("Tests")) {
    params {
        add {
            password("env.LITELLM_API_KEY", "credentialsJSON:0fbf8b85-76c5-40cc-940f-52b5a370c312")
        }
    }
}
