package patches.vcsRoots

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.ui.*
import jetbrains.buildServer.configs.kotlin.vcs.GitVcsRoot

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a vcsRoot with id = 'AiDevKitTeamcityConfig'
in the root project, and delete the patch script.
*/
create(DslContext.projectId, GitVcsRoot({
    id("AiDevKitTeamcityConfig")
    name = "ai-dev-kit-teamcity-config"
    url = "ssh://git@git.jetbrains.team/ai-development-kit/ai-dev-kit-teamcity-config.git"
    branch = "refs/heads/main"
    branchSpec = "refs/heads/*"
    authMethod = defaultPrivateKey {
        userName = "georgiizorabov"
    }
}))

