package ai.dev.kit.providers.mlflow

import ai.dev.kit.eval.utils.*
import ai.dev.kit.providers.mlflow.fluent.setupMlflowTracing

/**
 * A base abstract class for conducting evaluation tests on AI functionality.
 * The class manages multiple test runs within an experiment and provides mechanisms for evaluating
 * AI outputs against ground-truth data while logging the results into Mlflow.
 *
 * @param AIInputT The type of input provided to the AI system under test.
 * @param GroundTruthT The type of ground-truth data used for evaluation.
 * @param AIOutputT The type of output generated by the AI system.
 * @param EvalResultT The type of evaluation result representing scores or metrics assigned for a test.
 * @param experimentName The name of the experiment in MLflow where the test results will be logged.
 * @param runNamePrefix A prefix used for naming the runs within the experiment.
 * @param numberOfRuns The number of test runs to execute during the evaluation process.
 * @param tags A list of tags associated with each run, used for metadata purposes. The size of this list must match `numberOfRuns`.
 * @param userId any string.
 *              The user identifier for Mlflow.
 *              If not provided, the user ID will be derived from the environment variables or default settings.
 */
abstract class MlflowEvaluationTest<AIInputT : AIInput, GroundTruthT : GroundTruth, AIOutputT : AIOutput, EvalResultT : EvalResult>(
    experimentName: String = "Evaluation test",
    runNamePrefix: String = createRandomRunNameAdjectiveNounNumber(),
    numberOfRuns: Int = 1,
    tags: List<RunTag> = listOf(),
    userId: String? = null
) :
    BaseEvaluationTest<AIInputT, GroundTruthT, AIOutputT, EvalResultT>(
        experimentName,
        runNamePrefix,
        numberOfRuns,
        tags,
        MlflowEvaluationClient,
    ){
    init{
        setupMlflowTracing(userId)
    }
}