/*
 * Copyright © 2026 JetBrains s.r.o. and contributors.
 * Use of this source code is governed by the Apache 2.0 license.
 */

package ai.jetbrains.tracy.examples

import ai.jetbrains.tracy.core.TracingManager
import ai.jetbrains.tracy.core.fluent.Trace
import io.opentelemetry.api.common.AttributeKey
import io.opentelemetry.api.common.Attributes
import io.opentelemetry.api.trace.StatusCode
import io.opentelemetry.context.Context
import io.opentelemetry.exporter.logging.LoggingSpanExporter
import io.opentelemetry.sdk.OpenTelemetrySdk
import io.opentelemetry.sdk.resources.Resource
import io.opentelemetry.sdk.trace.SdkTracerProvider
import io.opentelemetry.sdk.trace.export.SimpleSpanProcessor

@Trace(name = "ProcessRequest")
fun processRequest(): String {
    println("Processing...")
    return "done"
}

/**
 * Creates a sample [OpenTelemetrySdk] configured with a [LoggingSpanExporter] for demonstration purposes.
 *
 * In a real application, replace this with your own SDK instance.
 */
fun initializeOpenTelemetry(): OpenTelemetrySdk {
    val resource = Resource.getDefault()
        .merge(
            Resource.create(
                Attributes.of(
                    AttributeKey.stringKey("service.name"), "my-ai-application",
                )
            )
        )

    val sdkTracerProvider = SdkTracerProvider.builder()
        .addSpanProcessor(SimpleSpanProcessor.create(LoggingSpanExporter.create()))
        .setResource(resource)
        .build()

    return OpenTelemetrySdk.builder()
        .setTracerProvider(sdkTracerProvider)
        .buildAndRegisterGlobal()
}

/**
 * Demonstrates integrating Tracy into an application with an existing OpenTelemetry SDK.
 *
 * If your project already configures an [OpenTelemetrySdk], pass it directly to Tracy via
 * [TracingManager.setSdk] instead of using `configureOpenTelemetrySdk`. Tracy spans are then
 * recorded within your existing trace hierarchy.
 *
 * This example shows how to:
 * - Pass a pre-configured [OpenTelemetrySdk] to Tracy using [TracingManager.setSdk].
 * - Create a parent span using your own tracer and activate its [Context], so that Tracy spans
 *   are recorded as its children.
 * - Annotate a function with [Trace] to generate a nested span.
 *
 * Running this example produces a trace rooted at a **run-app** span containing:
 * - A nested **ProcessRequest** span generated by [Trace].
 */
fun main() {
    val sdk = initializeOpenTelemetry()
    val tracer = sdk.getTracer("my-app", "1.0.0")
    val span = tracer.spanBuilder("run-app").startSpan()
    try {
        TracingManager.isTracingEnabled = true
        TracingManager.setSdk(sdk)
        Context.current().with(span).makeCurrent().use {
            processRequest()
        }
        span.setStatus(StatusCode.OK)
    } catch (e: Exception) {
        span.setStatus(StatusCode.ERROR, e.message ?: "Error")
        span.recordException(e)
        throw e
    } finally {
        span.end()
    }
}
